/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _REGISTERER_H_RPCGEN
#define _REGISTERER_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


#define REGISTERERSERV 0x20000001
#define GETIDVERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define GETID 1
extern  long * getid_1(void *, CLIENT *);
extern  long * getid_1_svc(void *, struct svc_req *);
extern int registererserv_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define GETID 1
extern  long * getid_1();
extern  long * getid_1_svc();
extern int registererserv_1_freeresult ();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_REGISTERER_H_RPCGEN */
