/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _REGISTERER_H_RPCGEN
#define _REGISTERER_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


#define REGISTERERSERV 0x20000002
#define GETIDVERS 2

#if defined(__STDC__) || defined(__cplusplus)
#define GETID 1
extern  long * getid_2(void *, CLIENT *);
extern  long * getid_2_svc(void *, struct svc_req *);
extern int registererserv_2_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define GETID 1
extern  long * getid_2();
extern  long * getid_2_svc();
extern int registererserv_2_freeresult ();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_REGISTERER_H_RPCGEN */
